### ISSUE TITLE
Add a chat interface

### ISSUE THREAD

**Issue by jeremija** [jeremija/peer-calls#12]
There could be a hotkey/button which displays an input box, or a whole new chat interface.

The chat messages should be sent to all participants through a P2P connection, not websockets.

The chat messages should be displayed in notifications as well.

Chat should work even if the browser doesn't have support for `getUserMedia`.

**Comment by khalaharvi** [comment]
Working on this issue

**Comment by jeremija** [comment]
@excelwebzone There is currently a way to send a message using websockets via the input box on the bottom-left. The messages will show on the top right. Ideally, there would be a way to set nicknames, and the chat messages would also use WebRTC (and maybe fall back to websocket).

![image](https://user-images.githubusercontent.com/1489493/48834526-55720c80-ed7e-11e8-86a6-c428b2707773.png)

**Comment by excelwebzone** [comment]
Right, I saw that.. do you have an estimate for it?

**Comment by excelwebzone** [comment]
@jeremija are you open to help me with a small project? shoot me an email.. 👍
