### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jeremija** [jeremija/peer-calls#16]

**Comment by lil5** [comment]
How about this?


---

## Env Variables

name | default | info
---|---|---
**PORT** | `3000` | Port number
**NODE_CONFIG_DIR** | `./config` | Where your configuration file reside, a [`./config/default.json`](https://github.com/jeremija/peer-calls/blob/master/config/default.json) must exist

---

**Comment by jeremija** [comment]
Sounds good! There is also the `config/custom-environment-variables.json` file that allows the users to specify the `baseUrl` and `iceServers` via `PEERCALLS_BASE_URL` and `PEERCALLS_ICE_SERVERS`. However, I do not think this will be read when peer-calls is installed as a module (whether a global or a local one) :(

**Comment by lil5** [comment]
A fix for that would be to add a `DOCUMENTATION.md` file but again breaking files usually causes users not reading it.
