### ISSUE TITLE
running peer-calls as localhost with invite codes

### ISSUE THREAD

**Issue by fredhampton** [jeremija/peer-calls#25]
I very much like peer-calls and I m wondering if its possible to run the app locally as localhost and if so will the url invite work ?

**Comment by jeremija** [comment]
You can run it locally, but keep in mind that video calling via WebRTC requires HTTPS, so you would need to start the https web server instead of http (a few lines would need to be changed), and you'd also need a valid certificate to prevent warnings about invalid certs.
