### ISSUE TITLE
How can I resolve the conference preview to people without a camera and microphone?

### ISSUE THREAD

**Issue by visorq** [jeremija/peer-calls#26]
that it needs to change in the code?
![screenshot_3](https://cloud.githubusercontent.com/assets/2658720/18891296/73ed6cb2-8526-11e6-9481-abc23a0a4309.jpg)

**Comment by thomastthai** [comment]
I ran into the same issue. I THINK it is because you are using http instead of https protocol. I remember reading about Google wanting WebRTC to be under https. In looking at the node scripts, I only see http not https for peer-calls.

**Comment by jeremija** [comment]
@thomastthai is right that WebRTC requires https, @visorq it should work if you access the server via localhost if that's the issue.

**Comment by thomastthai** [comment]
I ended up switching to SimpleWebRTC and running behind HTTPS and had no issues. Their node / express set up worked out of the box.
