### ISSUE TITLE
No attempt to establish a peer to peer connection

### ISSUE THREAD

**Issue by matikbird** [jeremija/peer-calls#29]
We were just talking about it in the other issue. @jeremija close up for a guy who has no idea what's like contributing to open source projects.

I just want to know how can I fixed,
What did you do in peercalls.com that works so well,

I had HTTPS set up,
Node.js aswell,
I checked STUN and TURN and did not understand so well the process of this.
Tried another ones and the same.

Thanks for anyone who's willing to help me and the package in advance.
https://mrkapl.science:3000

**Comment by MrDarkSkil** [comment]
If you want, this project work fine https://github.com/andyet/SimpleWebRTC

**Comment by jeremija** [comment]
Your site is down. There could be a number of issues. What do the logs say? Do websocket connection established? Are the handshake signals sent?

For the last one you're basically looking for this line:
```javascript    debug('peer: %s, signal: %o', user.id, signal);
```

**Comment by matikbird** [comment]
It's a whatever-site. I put it up just so anyone could help me track this issue, haha.
I'm sorry, it's up and running again, with PM2.

In the meanwhile, I was trying to make it work in my localhost.
```
 peer-calls:socket ready: fHONmsFpClpl9-Q5AAAA, room: 59a4b05d-fc86-4f92-a1f8-bcb534e572ba +0ms
  peer-calls:socket ready: fHONmsFpClpl9-Q5AAAA, room: 59a4b05d-fc86-4f92-a1f8-bcb534e572ba, users: [ { id: 'fHONmsFpClpl9-Q5AAAA' } ] +2ms
  peer-calls:socket ready: 0wbaROGucAgByT9mAAAB, room: 59a4b05d-fc86-4f92-a1f8-bcb534e572ba +4s
  peer-calls:socket ready: 0wbaROGucAgByT9mAAAB, room: 59a4b05d-fc86-4f92-a1f8-bcb534e572ba, **_users: [ { id: 'fHONmsFpClpl9-Q5AAAA' }, { id: '0wbaROGucAgByT9mAAAB' } ]_** +1m
```

Connected to server socket
Ready for connections
Connected users: 1
Connecting to peer...
Connected users: 2
Connecting to peer..

Clearly, it knows how many users are, so I'll take that as a good sign.
But it holds up on Connecting to peer.
https://mrkapl.science:3000 it's working now, I'm sure you can see something I'm missing.

Thanks a lot for the reply, @jeremija

**Comment by matikbird** [comment]
As a side note, I tried the project in a few VPS, and desktop's as well. All of them with the firewall OFF.

It might have something to do with the credentials, but if it works for you..
Have you tried downloading the repo now and do an ` npm install & npm start`
Dependences also might mess up with the config of PeerCalls. I tried downgrading Socket.IO and a few other dependences.

I will keep attempting to fix it, any help it's more than welcome (:

**Comment by jeremija** [comment]
Thanks for bringing this to my attention. However it looks like the SocketIO library has changed the way `socket.id`s are assigned, thus no attempt was made to initiate the connection because the comparison would fall.

This should be fixed as of today (aa2f3f4). Check the commit message for additional info.

**Comment by matikbird** [comment]
To make things easier when debugging, this is how it goes:
You enter the site, and it's all OK, but something it's failing in Socket.IO

![screenshot from 2016-11-22 13 16 23](https://cloud.githubusercontent.com/assets/12424545/20531764/819ba85e-b0b6-11e6-8864-6b58649259bb.png)

See those strange characters? **y``**
If we go to them, opening a new tab
![screenshot from 2016-11-22 13 18 37](https://cloud.githubusercontent.com/assets/12424545/20531806/a5bf1482-b0b6-11e6-85aa-639a2232872f.png)

**Comment by matikbird** [comment]
Oh, I was about to say it was Socket.IO!
Haha, I'll try it out just now and give you a feedback, @jeremija (:

**Comment by jeremija** [comment]
Those chars are fine, let me know if it works now.

**Comment by matikbird** [comment]
Yeap, that fixed.
Just so you know and just so we're clear..
I really love you right now, haha. Worked like a charm.

Amazing work, @jeremija 
I'll be more involved from now on.
