### ISSUE TITLE
Adding turn servers

### ISSUE THREAD

**Issue by ampc** [jeremija/peer-calls#34]
Hello, first of all thank you for creating such a simple project to play with WebRTC.
 I have the following question regarding TURN servers. Should I add them in `config/default.json` or is there any other solution?

Currently my `default.json`  is :
```{
    "iceServers": [
        {
            "url": "stun:stun.l.google.com:19302",
            "urls": "stun:stun.l.google.com:19302"
        },
        {
            "username": "hello",
            "url": "turn:turn03.uswest.xirsys.com:80?transport=udp",
            "credential": "world"
        },
        {
            "username": "hello",
            "url": "turn:turn03.uswest.xirsys.com:3478?transport=udp",
            "credential": "world"
        },
        {
            "username": "hello",
            "url": "turn:turn03.uswest.xirsys.com:80?transport=tcp",
            "credential": "world"
        },
        {
            "username": "hello",
            "url": "turn:turn03.uswest.xirsys.com:3478?transport=tcp",
            "credential": "world"
        },
        {
            "username": "hello",
            "url": "turns:turn03.uswest.xirsys.com:443?transport=tcp",
            "credential": "world"
        },
        {
            "username": "hello",
            "url": "turns:turn03.uswest.xirsys.com:5349?transport=tcp",
            "credential": "world"
        }
    ]
}
```

**Comment by jeremija** [comment]
As of ddb54a2, we are using [node-config][1], which means you can add create a `local.json` file to override the default configuration. There are other ways to [override the default configuration][2].

But what you wrote should also work. Note that the `url` is [deprecated][3], and you should use `urls` instead. In the default config there's both for backward compatibility.

[1]: https://github.com/lorenwest/node-config
[2]: https://github.com/lorenwest/node-config/wiki/Environment-Variables
[3]: https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer/url

**Comment by ampc** [comment]
OK,  I changed `url` to `urls` and it still didn't work on specific conditions (phone 4G + computer behind NAT firewall). Then I switched from Xirsys  to Twilio TURN servers and now it works. Thank you for the quick reply.
