### ISSUE TITLE
Turn server config

### ISSUE THREAD

**Issue by utan** [jeremija/peer-calls#40]
Hi, I installed Coturn server and username and password are incorrect, i get 401 in server logs, 

While testing with Spreed-webrtc works fine..  
How do I set up coturn or peercalls to work together?

Does peercall needs to hash the username, se this is what i got.

57: session 002000000000000003: realm domain.com> user <user>: incoming packet message processed, error 401: Unauthorised

**Comment by jeremija** [comment]
Hi @utan, can you share the value of `iceServers` in your config? (please mask actual username/password)

**Comment by utan** [comment]
I am away from my pc, but i am overwriting default peercall settings editing the default config..
My coturn server has the same realm and username set, but it wont accept it..

The username is sent in as set meanwhile spreed-webrtc sent like a hash as username...and same realm

**Comment by utan** [comment]
57: session 006000000000000003: closed (2nd stage), user <1502742494:CeTSMai82npnusi4ortyuxJbDqZhXPcB4JszAISysi> realm <mydomain.com> origin <>, local ip#here, remote someip:29443, reason: TCP connection closed by client (callback

Thats the payload of spreed-webrtc to the coturn server, which spreed has the same plain realm and usrername as set in peercall..

**Comment by jeremija** [comment]
Are you trying to use coturn's [--use-auth-secret][1] flaf?

> This option uses timestamp as part of combined username:
> usercombo -> "timestamp:username",
> turn user -> usercombo,
> turn password -> base64(hmac(input_buffer = usercombo, key = shared-secret)).

If so, can you make sure that you have `auth: 'secret'` property set in your iceServer config?

1: https://github.com/coturn/coturn/blob/master/README.turnserver

**Comment by utan** [comment]
Settings for my coturn Server, it is online but my testbed for peercall is at home in my computer.

 Run as TURN server only, all STUN requests will be ignored.
no-stun

# Specify listening port. Change to 80 or 443 to go around some strict NATs.
listening-port=8443
tls-listening-port=5349

# Specify listening IP, if not set then Coturn listens on all system IPs. 
#listening-ip=12.34.56.78
#relay-ip=12.34.56.78

# These lines enable support for WebRTC
fingerprint
lt-cred-mech
realm=domain.com

# Authentication method
use-auth-secret
static-auth-secret=somewords.

total-quota=100

# Total bytes-per-second bandwidth the TURN server is allowed to allocate
# for the sessions, combined (input and output network streams are treated separately).
bps-capacity=0

# This line provides extra security.
stale-nonce

log-file=/var/log/turnserver/turn.log
no-loopback-peers
no-multicast-peers

**Comment by utan** [comment]
Elaborate please, I am not using the setting u are asking me..
Should be set as u you suggested?

I will check for those options.. and enable them.

**Comment by utan** [comment]
Do u want me to use the console to see its content?
I will be able to to see its content later late tonight pacific time..

**Comment by utan** [comment]
I don't same lines but this ones in my Coturn server

 usercombo -> "timestamp:myuser"
 turn user -> usercombo
 turn password -> base64(hmac('mypassword', usercombo))

And set my usercombo content and mypassword in PeerCall default settings?

Does it look correct?

**Comment by jeremija** [comment]
Try updating your config file to contain the following:

```json
{
  iceServers: [{
    urls: "yourdomain.com",
    username: "<your_coturn_username>",
    secret: "<your_coturn_secret>",
    auth: "secret"
  }]
}
```




On Aug 14, 2017 10:00 PM, "Neumann Valle" <notifications@github.com> wrote:

I don't same lines but this ones in my Coturn server

usercombo -> "timestamp:myuser"
turn user -> usercombo
turn password -> base64(hmac('mypassword', usercombo))

And set my usercombo content and mypassword in PeerCall default settings?

Does it look correct?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jeremija/peer-calls/issues/40#issuecomment-322356719>,
or mute the thread

**Comment by utan** [comment]
I am sorry, I am more confused, should I set the coturn server the way I discribed above and then setup  PeerCalls as ur previous reply?
I am new to this, and not as proficient as I thought I was..

**Comment by utan** [comment]
Hi it's working now.. 

#for PeerCalls settings
fingerprint
lt-cred-mech
#single static user details for long-term authentication:
user=user-you-want-to-user:12352453256482331
#your domain here:
realm=domain.com

Found the answer at 
https://stackoverflow.com/questions/26110412/is-long-term-credentials-authentication-mechanism-required-for-webrtc-to-wor
