### ISSUE TITLE
Explain STUN server in README.md

### ISSUE THREAD

**Issue by lil5** [jeremija/peer-calls#47]
When looking threw the code I saw the a link to google:
https://github.com/jeremija/peer-calls/blob/fee565a4e35963cf56efbfc7542cfa74deaa5312/config/default.json#L4-5

Reading about STUN server I found out it that is only used to find out what the WAN IP is and does not pass any other information.
https://www.youtube.com/watch?v=JrxSDIJv5xs

It might be a good idea to explain it in the README.md

**Comment by jeremija** [comment]
We could add a link to this site maybe?

https://www.twilio.com/docs/stun-turn/faq

**Comment by lil5** [comment]
Looks good :+1:

**Comment by lil5** [comment]
#16
