### ISSUE TITLE
package.json uses old version

### ISSUE THREAD

**Issue by lil5** [jeremija/peer-calls#49]

**Comment by lil5** [comment]
This could be fixed at pr #48 see https://github.com/jeremija/peer-calls/pull/48#issuecomment-435632322

**Comment by lil5** [comment]
peer-calls - npm - https://www.npmjs.com/package/peer-calls

Shows 2.0.6 while package.json still 2.0.5

**Comment by lil5** [comment]
I advice using `--tag beta` before publishing to stable. Npm doesn't allow version rewrites.

> Fails if the package name and version combination already exists in the specified registry.
> 
> Once a package is published with a given name and version, that specific name and version combination can never be used again, even if it is removed with npm-unpublish.

**Comment by jeremija** [comment]
This is my bad. I think I published a package before pushing to GitHub, and then I realized you've done all that work already so I didn't want to discredit your pull request.
