### ISSUE TITLE
Regarding Apple Desktops & IPhones

### ISSUE THREAD

**Issue by mdemarco1234** [jeremija/peer-calls#60]
the streaming does not work on the MAC desktop.  Images are being streamed from a smartphone to a website on the MAC desktop but the streamed video is not appearing. Is there any solution for MAC's? Can it be fixed?

**Comment by jeremija** [comment]
Hi @mdemarco1234,

Thanks for the bug report. I have a few questions:

1. Which browsers and versions are you using?

2. Just to clarify - you see the video on your mobile phone, but not on the Mac?

3. Have you granted camera access permissions for the browser and the website on your phone? 

4. Are you testing this via peercalls.com, or using your own (local or remote) server?

**Comment by mdemarco1234** [comment]
Hi,


   1.     the android was using chrome that was live streaming but the mac pro and the ios devices were using the latest safari version on the market

   2.     chrome on the android or desktop works. meaning streaming and receiving

   3.     yep

   4.     used my own forked version.

   5.     the camera opened up on safari on the mac pro meaning you can see yourself when the button is activated. What you can't do is received the video live streamed
            from the android so its an inbound reception problem on those devices. Some say it is codecs and one said to use adapter.js


  1.  Which browsers and versions are you using?

  2.  Just to clarify - you see the video on your mobile phone, but not on the Mac?

  3.  Have you granted camera access permissions for the browser and the website on your phone?

  4.  Are you testing this via peercalls.com, or using your own (local or remote) server?

—





________________________________

**Comment by jeremija** [comment]
Could you please try clicking on the icons that are dark in Safari? Safari seems to prevent multiple videos from autoplaying and they need to be manually clicked to start playing.

Also could you please test this on peercalls.com and let me know if you can reproduce the issue? I just pushed v2.0.8 which updated a lot of dependencies to more recent versions.

**Comment by mdemarco1234** [comment]
Sure.  Another question with the understanding there latencies  in streaming delivery are unavoidable as even facebook has freeze frame on their face time.  From the sender of the streaming's end, what type of connection  speed would assure the best delivery of streaming video in the minimal amt of time?  What other variables are in our playing field we can control to assure the most minimal delivery times




________________________________

**Comment by mdemarco1234** [comment]
Hi,


         It works.


    Thanks,

    Michael




________________________________
