### ISSUE TITLE
How to enable https instead of http?

### ISSUE THREAD

**Issue by jimver04** [jeremija/peer-calls#64]
Hi, 

I have installed your code it in Ubuntu 16.04 server successfully. The text conversation works well. But mic and camera is blocked by default as it is running in http mode but not https.

It is necessary to have it with SSL because the recent versions of Firefox and Chrome do not allow access to camera and microphone in http mode.

I already have replaced the cert.example.pem and key in config folder but i think they are ignored. There should be a switch somewhere in your code but I can not find it. 

 - Device: [e.g. laptop]
 - OS: [e.g. Windows 10]
 - Browser [e.g. Firefox 69 Quantum, and Chrome 77]

Thanks in advance,
D.

**Comment by jeremija** [comment]
You need to set the path to the certificates in the config file. Have a look at the following file:

https://github.com/jeremija/peer-calls/blob/master/src/server/server.js#L9,L14

You can create a new file called `config/local.json` and set the paths there:

 ```json
{
  "ssl": {
    "cert": "./config/cert.example.pem",
    "key": "./config/cert.example.key"
  }
}
```

**Comment by jimver04** [comment]
Hey, it works ! You saved my day.
I wish this was written in the instructions Readme as I was struggling 2 hours.

D.

**Comment by jeremija** [comment]
Create a pull request :) Glad I was able to help!

**Comment by ppriede** [comment]
> You need to set the path to the certificates in the config file. Have a look at the following file:
> 
> https://github.com/jeremija/peer-calls/blob/15e870a0d5bb2ddd8b27e92db15813c3432fe7a5/src/server/server.js#L9,L14
> 
> You can create a new file called `config/local.json` and set the paths there:
> 
> ```json
> {
>  "ssl": {
>    "cert": "./config/cert.example.pem",
>    "key": "./config/cert.example.key"
>  }
> }
> ```

For future reference:
The file to inclue in the config folder is:
config/local.**yaml**

Cheers!
