### ISSUE TITLE
Desktop Sharing

### ISSUE THREAD

**Issue by StephanKrauss** [jeremija/peer-calls#70]
Hello,

can the program peer-calls share the desktop ?

I am looking for a program that can forward the desktop
or the recording of an external webcam.
This program is for a school.

Sincerely, Stephan

**Comment by jeremija** [comment]
I just added experimental support for desktop sharing in v3.0.4. I would appreciate if you could test it and let me know does it work for you.

<img width="205" alt="image" src="https://user-images.githubusercontent.com/1489493/76314036-5e218580-62d6-11ea-82f0-75cf73b315a9.png">

**Comment by StephanKrauss** [comment]
Hi there,

Thank you for your prompt reply.
I support a school in my free time.
http://www.oberschule-bergstadt-schneeberg.de/

We expect a corona epidemic in Germany.
I am looking for a way to a small extent
to convey knowledge via the Internet.

Desktop sharing and simplifying the URL is important!
One question please.
How many people can use peer calls at the same time?
Are there any practical experiences?

Sincerely yours

Stephan

**Comment by jeremija** [comment]
Thanks for sharing the details. In the current implementation of peercalls, the peers create a mesh network (each peer sends audio/video data to every other peer). 

If peers are unable establish direct connections, and a relay ([TURN](https://en.wikipedia.org/wiki/TURN)) server is configured, it will be used instead. This means that the video streams willl be routed through this server.

For example, if there are 3 peers using the TURN server, the TURN server would use the bandwith for a total of 6 video streams. To generalize, if `N` peers are sending and receiving video, there will be a total of `N*(N-1)` video streams being sent and received.

I am hosting my own TURN server on peercalls.com, but I do not have the budget for a powerful server so it could potentially run out of bandwidth in a worst-case scenario where there are multiple rooms with 20+ users, with each peer using the relay server. Were you thinking of self-hosting, or using an existing cloud solution?

That said, someone has already asked a question about using peercalls for rooms with many users in issue #37.  It seems like the best way to support lots of users would be to use a [MCU](https://webrtcglossary.com/mcu/) (multipoint conferencing unit) or a [SFU](https://webrtcglossary.com/sfu/) (selective forwarding unit) server, such as [kurento](https://github.com/Kurento/kurento-media-server). To make peercalls working with such a server, some changes would need to be made in the signalling logic. I am not sure how much work that is at this point.

As for simplifying the URL, users can create a room with any name by modifying the URL part after the `/call/` part. For example, this is a valid call URL: https://peercalls.com/call/DieSchule.

Here's some additional links to learn more about WebRTC:

1. https://temasys.io/six-things-need-know-webrtc-sfus/
2. https://bloggeek.me/webrtc-multiparty-video-alternatives/
3. https://bloggeek.me/turn-public-ip-address/
4. https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/
5. https://github.com/coturn/coturn

Hope this helps! Good luck in fighting the coronavirus. I am currently based in Croatia and we have an increasing number of cases as well.

**Comment by StephanKrauss** [comment]
Hello,

i think i will use a virtual server.
The hoster is then.
https://www.hosteurope.de/Server/Virtual-Server/
'starter' or 'starter plus' Server.


It will be an Ubuntu server.
I want to rebuild the Ubuntu server.
Docker and docker-compose are to be installed.
I tested this on a local server.

2 things are important to me.
1. We want to send the URL to the students using WhatsApp.

I can imagine the following URL.
http.//meiDomain/room/myRoomNumber
I saw 
https://appr.tc/
as an example.

2. Desktop sharing must be possible.
It should be possible to switch between desktop sharing and webcam.

When I have converted a room into an online studio, I send some pictures.

Sincerely yours

Stephan

**Comment by jeremija** [comment]
How many daily users are you expecting?

How many simultaneous classes and users per class?

> 1. We want to send the URL to the students using WhatsApp. I can imagine the following URL.
http.//myDomain/room/myRoomNumber
> I saw https://appr.tc/ as an example.

I added an input field in v3.0.5 which allows the users to specify a custom room name:

<img width="351" alt="image" src="https://user-images.githubusercontent.com/1489493/76427379-81b6ff80-63ac-11ea-911a-2135104b1bc5.png">

> 2. Desktop sharing must be possible.
> It should be possible to switch between desktop sharing and webcam.

As I mentioned previously, sharing the desktop is already possible since v3.0.4 and webcam does not need to be disabled for this:

<img width="205" alt="image" src="https://user-images.githubusercontent.com/1489493/76314036-5e218580-62d6-11ea-82f0-75cf73b315a9.png">
