### ISSUE TITLE
Start testing peer-calls

### ISSUE THREAD

**Issue by StephanKrauss** [jeremija/peer-calls#72]
Germany , Leipzig 12.03.2020 07:36

Hello,

we will today start the testing of peer-calls.
After the test, i will get an information about the results.

Greetings Stephan

**Comment by jeremija** [comment]
Thanks for letting me know. I'm curious to hear the results.

In case you experience connectivity issues, you might need to install and
configure a TURN server. I use coturn and can share the configuration files
privately if you need them.

**Comment by StephanKrauss** [comment]
Hello,

we did a first test. This test was carried out on our intranet.
It was not possible to make a connection. The error message appeared in the Firefox web tool: 'TypeError: navigator.mediaDevices is undefined'

Sincerely, Stephan

**Comment by StephanKrauss** [comment]
Hello,

is there a public demo ?

Your sincerly Stephan

**Comment by jeremija** [comment]
Which version of Firefox are you using? My guess is that it is not an up-to-date version.

Public demo is available here: https://peercalls.com

**Comment by jeremija** [comment]
Also it could be this (from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)):

> # Encryption based security
>
> The getUserMedia() method is only available in secure contexts. A secure context is one the browser is reasonably confident contains a document which was loaded securely, using HTTPS/TLS, and has limited exposure to insecure contexts. If a document isn't loaded in a secure context, the navigator.mediaDevices property is undefined, making access to getUserMedia() impossible.

Are you using using HTTPS?

**Comment by StephanKrauss** [comment]
Hello, we're testing again tonight.
Our intranet has too many restrictions.
 We want to test with the URL :: https://peercalls.com.

Sincerely yours

Stephan
