### ISSUE TITLE
Don't work for public users, just for intranet

### ISSUE THREAD

**Issue by TechArea** [jeremija/peer-calls#76]
**Describe the bug**
The website can be loaded, but if you want to join, there is an interruption

**Bug Report Checklist**

- [X] I have granted camera/microphone access permissions while testing
- [x] This bug is reproducible on https://peercalls.com

**To Reproduce**
1. Go to https://peer.crashlog.ch
2. Click on "start session"
3. Click on "join call"

**Expected behavior**
if I access from the local net via domain, then it works with several participants. As long as all participants are in the intranet it works well. If I come from outside, then it does not work.

**Screenshots**
not available.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser safari
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.3.1
 - Browser stock browser, safari
 - Version: latest

**Additional context**
Server runs on port 3000 and is routed with HAProxy with SSL.

I'm not a such "pro", but I couldn't find the error on my side, so I suppose, the error must be on your side.

**Comment by jeremija** [comment]
If you cannot reproduce this on peercalls.com, then it is not a bug. I assume you are testing this within a corporate network? If so, perhaps the corporate firewall is blocking access to devices on the internal network. Peercalls.com is configured to use a TURN server (coturn), which will relay traffic when a direct connection cannot be established. The default configuration uses only a public STUN server, which is not enough in some situations.

**Comment by TechArea** [comment]
Ok. I'm behind a Firewall.
Can you please tell me which ports and protocols except tcp/udp on port 443 must be open?

**Comment by TechArea** [comment]
AbortError: The operation was aborted.
Peer connection closed
A peer connection error occurred
Connecting to peer...
Connected users: 2
Connected users: 1
Ready for connections
Connected to server socket

**Comment by jeremija** [comment]
From [Wikipedia](https://en.m.wikipedia.org/wiki/STUN#Design):

> The standard listening port number for a STUN server is 3478 for UDP and TCP, and 5349 for TLS. 

However, the default STUN server configured is stun.l.google.com:19302, since Google's STUN servers use 19302 instead of 3478.

**Comment by TechArea** [comment]
I've to reopen this case.
Now peercalls doesn't work for me in any way.
Also not on your homepage peercalls.com
I've tried different scenarios.
UPC to UPC -> not working
Swisscom to UPC-> not working
Sunrise to Salt-> not working

It works if both users are behind the same Firewall, else it doesn't work

**Comment by jeremija** [comment]
Sorry to hear that it doesn't work. I want to debug this. Can you join for a chat at Gitter: https://gitter.im/peer-calls/troubleshooting ?

**Comment by robinpham** [comment]
I have get the same this issues.
I deployed on aws, and run coturn.
1. passed with: the same internet service provider
2. Failed if participants are come other internet service provider
please help me to explain/ resolve this issues !.
Thanks you!

**Comment by jeremija** [comment]
Hi @robinpham,

Can you test your coturn server at: https://test.webrtc.org ?

You don't need to share your mic & camera there, I'm most interested in results of Network and Connectivity.

Make sure you enter your TURN settings here and leave the STUN server blank:

![image](https://user-images.githubusercontent.com/1489493/77350872-6d281f00-6d3d-11ea-8ae3-593df959aa38.png)

There are two ways of figuring out the configuration:

a) Open the call page on PeerCalls and run this in the developer console:

```javascript
JSON.parse(document.getElementById('iceServers').value)
```

b) Running this code snippet from root of peer calls config directory.

```bash
node -e 'console.log(require("./lib/server/turn").processServers(require("./lib/server/config").config.iceServers))'
```

If peercalls is installed as as node module, replace `./lib with  `./node_modules/peer-calls/lib`.

When using docker, run:

```
docker exec -it CONTAINER_ID node -e 'console.log(require("./lib/server/turn").processServers(require("./lib/server/config).config.iceServers))'
```

replace CONTAINER_ID with the correct container ID.

**Comment by robinpham** [comment]
Thanks you for  your help full.

As your solution, i tested, and failed.

![image](https://user-images.githubusercontent.com/19989512/77615946-23b91900-6f63-11ea-9515-af8d71423c96.png)

I allowed port 3478 / udp, 1000: 32768 / udp.
Up to now, I have not successfully configured, failed tested: https: //test.webrtc.org.

Because I don't have much experience deploying on aws.

Currently, the application I have deployed only runs on the same  internet service provider.

I would like you to explain/ resolve this issues !.

**Comment by jeremija** [comment]
Try also enabling 3478 tcp, and 5349 for tcp and udp, and rerun the tests (assuming you're using the defaults for coturn):

From https://github.com/coturn/coturn/wiki/turnserver:

>  -p, --listening-port <port> TURN listener port for UDP and TCP listeners (Default: 3478). Note: actually, TLS & DTLS sessions can connect to the "plain" TCP & UDP port(s), too - if allowed by configuration. For example, the default listening port can be set to 80 or 443, to go around some strict NATs. Remember that ports < 1024 may require superuser privileges to start the turnserver process.
> --tls-listening-port <port> TURN listener port for TLS and DTLS listeners (Default: 5349). Note: actually, "plain" TCP & UDP sessions can connect to the TLS & DTLS port(s), too - if allowed by configuration. For example, the default tls listening port can be set to 443, to go around some strict NATs. Remember that ports < 1024 may require superuser privileges to start the turnserver process. For secure TCP connections, we currently support SSL version 3 and TLS versions 1.0, 1.1, 1.2. For secure UDP connections, we support DTLS version 1.

**Comment by robinpham** [comment]
Thanks you!.
Based your solution, i reviewed my app coturn.

I detected an error when i start "turnserver"

![image](https://user-images.githubusercontent.com/19989512/77753865-e5078980-705c-11ea-988f-353412671b31.png)

Im trying to resolve.

I would like you to explain/ resolve this issues !.

**Comment by jeremija** [comment]
Hi @robinpham, please contact the [coturn](https://github.com/coturn/coturn) team for support for coturn.

**Comment by R0GGER** [comment]
Why closed? Problem still exists...

**Comment by jeremija** [comment]
Because I discusses this issue with OP in Gitter and the problem was resolved. Are you experiencing this issue on peercalls.com, or on a locally hosted instance?

**Comment by prologic** [comment]
Hey @jeremija I was reading through this issue and have run into similar problems in the past with _some_ (_only some_) users:

```
Peer connection closed
A peer connection error occurred
Peer connection established
Connecting to peer...
Connected users: 2
Connected users: 1
Dialling...
Connected users: 1
Dialling...
Connected to server socket
```

This is what i see on my end, and I believe my peers see a similar thing on their end too.

But **NB** my PeerCalls instance (https://meet.mills.io) works for _most_ folks I use it with just fine.

So my question is this:

- What are the possible reasons this might fail to connect in general?
- Failure from the other peer's side to contact Google's STUN servers? (_I use the defaults_)
- Do I need a Coturn server at all? (_this is something I've never understood_)

I'd like to basically figure out how to make my instance work with some other folks that it doesn't work for. I have one friend that lives closeby where it consistently fails for him, so I can at least have a reproducer.

**Comment by jeremija** [comment]
Hi @prologic, I see you're using peer calls in mesh (peer to peer) mode, perhaps you'll have better success running it in SFU mode and exposing the ephemeral UDP as well as TCP ports on your server.

For example:

```yaml
network:
  type: sfu
  sfu:
    interfaces:
    - eth0
    protocols:
    - udp4
    - udp6
    - tcp4
    - tcp6
    tcp_listen_port: 8443
    udp:
      port_min: 9000
      port_max: 9010
```

Then make sure incoming connections to TCP port 8443 and UDP port range 9000-9010 are allowed on your server.

This should cover 99% of the connection issues, but the traffic will be routed through the server rather than peer to peer.

Unfortunately different ISPs across the world have different rules and sometimes network firewalls or routers don't allow peer to peer connections. The coturn server helps in those cases. The coturn server can be configured with both mesh and SFU network types, but a SFU is better suited for conferences with more than two people because each user uploads their video only once. Also, since the SFU server is already publicly exposed, users have a better chance of connecting successfully, even without the coturn server.

Hope this helps!

**Comment by prologic** [comment]
I see Thank you for this explanation @jeremija 🙇‍♂️ This helps clear things up a lot! It's a shame I can't run the instance in both modes and have a way to pick one over the other or even fallback if p2p doesn't work? I _might_ be just smoking crack though 😅

**Comment by prologic** [comment]
In any case I'll have a go at reconfiguring my instance to use SFU mode for better experience for folks I video conf with around the globe 👌

**Comment by prologic** [comment]
@jeremija One final question on this (_hopefully it also serves as good documentation, maybe we can put this in a Wiki somewhere?_ -- Q: Is an alternative solution that can cater for both p2p/mech and sfu is to configure PeerCalls to also use a TURN server such as coturn?

Basically what I've found in practise is setting my PeerCalls instance to use SFU networking also exhibits _some_ problems with _some_ people and has this really nasty side-effect I don't really like of centralising all the traffic to one point, increasing the CPU, Memory and Network I/O of my instance unnecessarily (_I have graphs to show this!_)

**Comment by jeremija** [comment]
That's a little tricky. Some services enable P2P when there's only two users and then switch to SFU as soon as the third user joins, but it would be tricky to handle this gracefully, at least with the current state.

One thing that we can do to enable a third mode that would enable the user to pick SFU or P2P when they are creating a room. I realize it's not an ideal solution, but could help alleviate some of the issues.

**Comment by jeremija** [comment]
> Is an alternative solution that can cater for both p2p/mech and sfu is to configure PeerCalls to also use a TURN server such as coturn?

Yeah the coturn server can relay traffic and it allows those users that can't use the SFU directly to get around their NATs. But all the traffic is then relayed through that TURN server.

**Comment by prologic** [comment]
But if you had your instance configured in mesh networking with a coturn server some connected peers would go via the coturn SFU while others that can p2p would   directly rite between themselves?

**Comment by jeremija** [comment]
You can have a TURN server configured with SFU (coturn is not an SFU) or P2P, but the Peer Calls server itself cannot combine peers connected via P2P and SFU, it's all or nothing because of the way connections are initialized.
