### ISSUE TITLE
Feature request: seed nickname from HTTP auth user name

### ISSUE THREAD

**Issue by sigurg** [jeremija/peer-calls#77]
First of all: thank you for your work, peer-calls was quite effortless to set up and works great.

My instance actually runs behind a apache2 reverse proxy which requires HTTP basic authentication for all requests.
This is where my feature request comes in: right now every user that connects gets assigned a random UUID as nickname.
It would be great if I could peer-calls somehow tell to use the HTTP auth username as default, e.g. via a request header such as `X-Forwarded-User` or similar.

**Comment by jeremija** [comment]
@sigurg Can you test 3f9b41a and let me know if it works for you?

**Comment by sigurg** [comment]
Wow, that was fast...
Works like a charm, thank you so much!
This makes meeting-calls so much easier... :)

**Comment by jeremija** [comment]
Glad to hear it! Just published v3.0.17 🍻

**Comment by sigurg** [comment]
If you want to add a configuration example, here's my apache config:

    # peer-calls
    RewriteRule            ^/peercalls$ /peercalls/ [R=301]   # always append trailing slash to URI
    # reverse proxy for websockets
    RewriteCond           %{HTTP:Upgrade}  =websocket [NC]
    RewriteRule            ^/peercalls/ws/$(.*)  ws://localhost:3000/peercalls/ws/$1 [P,L]
    # reverse proxy for normal http requests
    ProxyPass               /peercalls/               http://localhost:3000/peercalls/ nocanon
    ProxyPassReverse  /peercalls/               http://localhost:3000/peercalls/
    <Location /peercalls>
        # enable basic auth
        AuthType Basic
        AuthName "MyRealm"
        AuthUserFile /path/to/htpasswd
        Require valid-user

        # add X-Forwarded-User header with username (REMOTE_USER)
        RequestHeader unset X-Forwarded-User
        RewriteCond %{REMOTE_USER} (.+)
        RewriteRule .* - [E=RU:%1,NS]
        RequestHeader set X-Forwarded-User %{RU}e
    </Location>

Run the follwing shell commands (as root) to enable required apache modules:

    a2enmod proxy
    a2enmod proxy_http                                                                                
    a2enmod proxy_wstunnel
    a2enmod rewrite

Thanks again!

**Comment by jeremija** [comment]
Thanks for sharing!
