### ISSUE TITLE
Error: NotAllowedError: The request is not allowed by the user agent or the platform in the current context.

### ISSUE THREAD

**Issue by jespoting** [jeremija/peer-calls#78]
*Describe the bug**
It only works if I call localhost directly. Inside the same computer with Firefox and in localhost you can find the cameras and the microphone and the video conference works.
If I configure to listen in the host ip, in my case 192.168.1.120 works the app from the same machine and same browser "firefox" but the videoconference does not work. I get the error I show above. I have not enabled the firewall and I am running it from the same machine.

Indicate that in the chromium browser it doesn't work neither in localhost nor in the host ip

**Bug Report Checklist**

- [ YES] I have granted camera/microphone access permissions while testing
- [ NO] This bug is reproducible on https://peercalls.com

**To Reproduce**

**Expected behavior**It does not work from the ip of the equipment, it only works from the same machine and whenever localhost is called. Indicate that I am referring to the video conference. The webapp does work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 10 BUSTER
 - Browser chrome 
 - Version 80.0.3987.149 

**Smartphone (please complete the following information):**
 - Device: Xiaomi MI9
 - OS: Android 10QKQ1
 - Browser Firefox and Chrome
 - Version 68.6 and 80

**Additional context**
The server will only run within the local network or vpn. At this time the test is inside the server.
Port 3000 is listened to and tests have been made with the default network and the local ip of the server

Listening on { address: '::', family: 'IPv6', port: 3000 } +0ms
and
Listening on { address: '192.168.1.120', family: 'IPv4', port: 3000 }

**Comment by jeremija** [comment]
Recent versions of browsers have stopped exposing the camera API when HTTPS is not used. Use the provided example certificates or generate your own for testing locally. Set the paths to certificate files using the `ssl.cert` and `ssl.key` in the YAML config file, or set the followng environment variable:

```
PEERCALLS__SSL='{"cert": "/path/to/cert.pem", "key": "/path/to/cert.key"}'
```
