### ISSUE TITLE
iframe

### ISSUE THREAD

**Issue by phuongnguyen2511** [jeremija/peer-calls#80]
Hello,
I am having issues with <iframe src = "https://peercalls.com/call/d8e150d4-ea73-4507-be4b-48dac0aa522e" style = "width: 100%; height: 100vh;"> </iframe>.
I cannot click the join call button ...
Thank you ...
![Capture](https://user-images.githubusercontent.com/56812712/77890013-f89f3400-7298-11ea-8b23-347a17b8e289.PNG)

**Comment by jeremija** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

> If you're using getUserMedia() within an <iframe>, you can request permission just for that frame, which is clearly more secure than requesting a more general permission. Here, indicate we need the ability to use both camera and microphone:
> 
> ```html
> <iframe src="https://mycode.example.net/etc" allow="camera;microphone">
> </iframe>
> ```
