### ISSUE TITLE
Switch Camera

### ISSUE THREAD

**Issue by ahmetozalp** [jeremija/peer-calls#81]
Is it possible and how do I change the camera for mobile devices during the live broadcast?

**Comment by jeremija** [comment]
You can press the hang up button and pick your camera again. Unfortunately it is not possible to change the camera stream without interrupting the audio stream at the moment.

**Comment by ahmetozalp** [comment]
Doesn't the FacingMode user and environment event solve the problem?

**Comment by jeremija** [comment]
In my experience `facingMode: 'user'` is unreliable, at least in Firefox Android. A possible alternative would be to cycle between all or the first two cameras found. Closing as duplicate of #30.
