### ISSUE TITLE
Encryption ?

### ISSUE THREAD

**Issue by fredhampton** [jeremija/peer-calls#83]
Are peer calls encrypted ?

**Comment by jeremija** [comment]
Yes, the WebRTC specs mandate encryption. The peercalls.com server uses a standard TLS encryption and browsers will prevent access to `navigator.mediaDevices.getUserMedia` if a self-hosted instance is configured without TLS.

Depending on the ICE servers configured, some network information might be transferred to a third party to help establish a peer connection. On peercalls.com we're hosting our own TURN server so no third parties are involved.

The connections between peers are always end-to-end encrypted, even in the case of using a TURN server when the peers are unable to establish a direct connection. This is all a part of the WebRTC spec and browsers do all the heavy lifting there.

Note that I'm currently working on implementing an SFU server to support casting or video to a larger audience. The downside of an SFU is that the streams need to be decoded server-side, and the server then distributes the videos as needed to other peers. When implemented, I'm going to add it as an option in the application config file.

Links for more reading:

1. https://webrtc-security.github.io/
2. https://www.3cx.com/blog/voip-howto/stun-details/
3. https://en.wikipedia.org/wiki/Traversal_Using_Relays_around_NAT

I'm going to close this issue, but feel free to comment if you have any more questions or concerns.

**Comment by fredhampton** [comment]
Great !!!!!
Thanks so much for all you are doing !!!!
