### ISSUE TITLE
write on screen when camera is off

### ISSUE THREAD

**Issue by ahmetozalp** [jeremija/peer-calls#84]
Hello, I will send some features like taking a screenshot in peerconnect in a few days but I have to do this too. If any camera is off, I want to write the screen, how can I do this? (my english bad, translate use)

**Comment by jeremija** [comment]
Thanks @ahmetozalp. What do you wish to write on screen? Draw? Or show a label when no video is visible?

**Comment by ahmetozalp** [comment]
just write something. In the big and small window, I will edit the text to be written

how can I do it?

**Comment by jeremija** [comment]
Take a look at the Chat.tsx and Input.tsx components and see how messages are being sent and received there. I think it should give you a good starting point.

**Comment by ahmetozalp** [comment]
thank you I will look

**Comment by ahmetozalp** [comment]
I think I can't explain my problem so I will try again..


![GitHub Logo](https://i.ibb.co/FwwrCsD/Ekran-Resmi-2020-04-06-03-43-06.jpg)

How do I specify my step 2 says camera is off?

**Comment by ahmetozalp** [comment]
2. step black screen add offline icon
