### ISSUE TITLE
Browser tab duplication

### ISSUE THREAD

**Issue by litashg** [jeremija/peer-calls#86]
Hi, Jerko! 
I suddenly found that if I click "Duplicate browser tab" - I got an empty room with the same URL but the count of sockets in room increments. Maybe we got some way to block duplication or avoid cloning. 
 
![Screen Shot 2020-04-07 at 2 00 42 PM](https://user-images.githubusercontent.com/31222500/78661975-4db1fa00-78d8-11ea-8cb8-034b74dbfb59.png)
![Screen Shot 2020-04-07 at 2 01 01 PM](https://user-images.githubusercontent.com/31222500/78661980-4ee32700-78d8-11ea-8eed-4a2f2868f5e2.png)

**Comment by jeremija** [comment]
So this happens only when you use the duplicate option? I've tested this many times, but I'd copy and paste the URL manually and that works.

**Comment by jeremija** [comment]
Can you check if the value of `userId` is the same for the duplicated tab?

**Comment by litashg** [comment]
Yes, only if I use duplicate. If I copy/paste URL manually - all works perfectly. 

I make screenshots from the console. 

User 1 - connected via peercalls.com and created room manually
![Screen Shot 2020-04-07 at 2 06 59 PM](https://user-images.githubusercontent.com/31222500/78662563-4f2ff200-78d9-11ea-8d20-c9a953362bb1.png)

User 2 - connected via copy-paste 
![Screen Shot 2020-04-07 at 2 07 13 PM](https://user-images.githubusercontent.com/31222500/78662583-5b1bb400-78d9-11ea-949e-f2cea59dd22c.png)

User3 - duplicated 
![Screen Shot 2020-04-07 at 2 07 19 PM](https://user-images.githubusercontent.com/31222500/78662600-62db5880-78d9-11ea-8fe7-47bf57a0e050.png)

**Comment by litashg** [comment]
`userId` - is same on duplicated pages

**Comment by jeremija** [comment]
This is why it didn't connect. If you had another user connected it would connect normally. This would never happen in real life, unless somehow the UUIDs generated are the same and the probability for this is really low.

**Comment by litashg** [comment]
So if someone wants to open chat in a few tabs we should just ignore that? Count of users in the room will increment, and no new video streams appear.

**Comment by jeremija** [comment]
I guess so. We could also generate userIDs client side. Before a recent update, the socket ID was the main identifier. I changed it to userID generated on page render to keep the old peer connections alive on reconnect.

**Comment by litashg** [comment]
I'll try to filter duplicated connections, and redirect them to main page. Maybe it helps. Thank you for your answer!
