### ISSUE TITLE
WebRTC and buffer 

### ISSUE THREAD

**Issue by litashg** [jeremija/peer-calls#90]
Hello, Jerko! 
I have a question for you. We used webchat for an hour in 9 ppl and I thought that after some time browser take more and more RAM. After 1 hour it was nearly 1gb and user clients start to lag. 
Is it a data buffer? And if yes - how can I clear it from time to time.

**Comment by ahmetozalp** [comment]
I noticed that too, the browser is slowing down in firefox

**Comment by jeremija** [comment]
Thank you both for reporting this. This sounds like a memory leak in the browser. We don't do any stream processing in Peer Calls, and neither is `simple-peer`, which just wraps the calls to `RTCPeerConnection`. We're simply passing the streams around to `<video>` elements.

Can you run the profiler in DevTools and see if there's anything particular that's consuming increasing amounts of memory?

I'd also check out if `about:webrtc` in Firefox and `about:webrtc-internals` in Chrome have any more information about memory consumption.

**Comment by litashg** [comment]
Sadly to say, but I don't understand what is profiler talking about. I can send you json with results if you know what to do with it. I found one moment that I saw in Activity Monitor. Each time I go into chat Google Chrome Helper (Renderer) added to processes, and even I leave chat these helpers don't disappear. 
![Screen Shot 2020-04-09 at 11 10 46 AM](https://user-images.githubusercontent.com/31222500/78878942-e1600380-7a5b-11ea-8ce2-a31676e5581b.png)
![Screen Shot 2020-04-09 at 11 10 56 AM](https://user-images.githubusercontent.com/31222500/78878948-e329c700-7a5b-11ea-966e-72a6fdb6aa6e.png)

**Comment by jeremija** [comment]
You can take a memory snapshot from Dev Tools:

Firefox:

![image](https://user-images.githubusercontent.com/1489493/78884907-f76dc400-7a5b-11ea-95b5-5243ced52eda.png)

Chrome:

![image](https://user-images.githubusercontent.com/1489493/78884893-f2a91000-7a5b-11ea-96c6-022ce325e7bb.png)

**Comment by ahmetozalp** [comment]
![GitHub Logo](blob:https://imgur.com/2fed4aa3-2b07-4040-ac04-a3adc9a099a4)

**Comment by jeremija** [comment]
Thanks for sharing. It looks like only 19MB is in use. Does this size increase over time?

**Comment by ahmetozalp** [comment]
I have never watched from here, but if I notice it, I will look at it and share the screen image again. (translate)

**Comment by litashg** [comment]
Hi! I found that memory leaks are a problem of Chrome. Nothing we can do. Thanks to all of you!

**Comment by jeremija** [comment]
Can you share a link?

**Comment by litashg** [comment]
https://github.com/webtorrent/webtorrent/issues/551

**Comment by jeremija** [comment]
Thanks!
