### ISSUE TITLE
IOS - Chrome browser not working!

### ISSUE THREAD

**Issue by ahmetozalp** [jeremija/peer-calls#91]
Click: Youtube Video

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/G9u_QShuyYQ/0.jpg)](https://www.youtube.com/watch?v=G9u_QShuyYQ)

**Comment by ahmetozalp** [comment]
> No you can't use WebRTC in Chrome in iPhone / iPad because Chrome (and also Firefox) are only some cover over apple WebView (Apple doesn't let to use custom web engine on their platform). Sad is that it isn't clearly informed by Google and Mozilla because some people get confused and said "Yes chrome support WebRTC so it should work on iOS devices". Apple has not presented version of their browser and also webview with WebRTC.

Current status of it you could check http://iswebrtcreadyyet.com/


https://stackoverflow.com/questions/39790639/webrtc-support-on-chrome-browser-in-iphone-ipad

**Comment by jeremija** [comment]
Which iOS and Safari version are you using?

I am able to successfully connect on iOS 12.4.5 and latest iOS 13.

**Comment by ahmetozalp** [comment]
Iphone 11
Version: 13.3.1

**Comment by jeremija** [comment]
Could it be that another application on your iPhone is already recording video? I see a red recording icon before you click `Join Call`. Perhaps in another tab?

**Comment by ahmetozalp** [comment]
Safari working
Chrome notworking.

**Comment by ahmetozalp** [comment]
reverse screen on the back camera How can I fix this?

**Comment by jeremija** [comment]
Yes, you are right. It doesn't seem to work outside of Safari.

You should be able to choose a video under your nickname, where it says `Default Video` by default.

**Comment by jeremija** [comment]
For the reversal, you'd need to figure out which camera you got and based on that disable the `mirrored` CSS style in the `<Video>` component.

I've known about this issue for some time, but never had the bandwidth to fix it.

**Comment by ahmetozalp** [comment]
Go to android phone: https://peercalls.com/call/a

and select the back camera

mirroring class not working.

**Comment by jeremija** [comment]
I don't think I can reproduce your issue - my back camera is being mirrored (and this is a bug). Is this what you're experiencing?

**Comment by ahmetozalp** [comment]
The 'mirroring' class is working on the front camera, no problem, but when you run the rear camera, this 'mirroring' must be deleted.

**Comment by ahmetozalp** [comment]
I can detect the rear camera. I can delete the 'mirroring' class.
